[package]
name = "radish"
version = "0.2.0"
edition = "2018"

[dependencies]
rustc-hash = "1"
termcolor = "1.1.2"
clap = "2.34.0"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"

[dev-dependencies]
regex = "1"
lazy_static = "1.4.0"